### ISSUE TITLE
Issue with CSV processing using parallelism

### ISSUE THREAD

**Issue by vemonet** [RMLio/RMLStreamer#15]
I am using the Docker Flink deployment as explained in the [docker README](https://github.com/RMLio/RMLStreamer/tree/master/docker)

Here are the commands I am executing to run it in parallel:

JSON: works well
```
docker exec -it d2s-cwl-workflows_rmlstreamer_1 /opt/flink/bin/flink run -p 8 -c io.rml.framework.Main /mnt/workspace/RMLStreamer.jar --path /mnt/datasets/hgnc/mapping/json_mapping.rml.ttl --outputPath /mnt/workspace/import/rmlstreamer-json_mapping_rml_ttl-hgnc.nt --job-name "[d2s] RMLStreamer json_mapping.rml.ttl - hgnc" --parallelism 8 --enable-local-parallel
```

CSV: adding the parallelism to flink (` flink run -p 8`) causes an issue in the output file generation (for CSV only apparently)

If `-p` is set to 8, then instead of generating the output.nt file it will generate 8 directories, named `1/ 2/ 3/ 4/ 5/ 6/ 7/ 8/` which contain the content of the current dir where I run the command
```
docker exec -it d2s-cwl-workflows_rmlstreamer_1 /opt/flink/bin/flink run -p 8 -c io.rml.framework.Main /mnt/workspace/RMLStreamer.jar --path /mnt/datasets/hgnc/mapping/csv_mapping.rml.ttl --outputPath /mnt/workspace/import/rmlstreamer-csv_mapping_rml_ttl-hgnc.nt --job-name "[d2s] RMLStreamer csv_mapping.rml.ttl - hgnc" --parallelism 8 --enable-local-parallel
```

Is it the right way to use parallelism with the RMLStreamer? 

Thanks

**Comment by vemonet** [comment]
Could it be related to those changes? https://github.com/RMLio/RMLStreamer/commit/e0a930a6b9db50be5d26f6c6c16d3a51727b800d

**Comment by ghsnd** [comment]
Hi @vemonet 

The use of parallelism is correct. However, since RMLStreamer [version 2](https://github.com/RMLio/RMLStreamer/releases/tag/v2.0.0),
parallelism is set by Flink's `-p` option only, the `--parallelism` parameter is discarded.

In short, now your command would look like:

```
docker exec -it d2s-cwl-workflows_rmlstreamer_1 /opt/flink/bin/flink run -p 8 \
-c io.rml.framework.Main /mnt/workspace/RMLStreamer.jar \
toFile \
--mapping-file /mnt/datasets/hgnc/mapping/json_mapping.rml.ttl \
--output-path /mnt/workspace/import/rmlstreamer-json_mapping_rml_ttl-hgnc.nt \
--job-name "[d2s] RMLStreamer json_mapping.rml.ttl - hgnc"
```
Assuming you use Flink 1.10.

The output would be a *directory* `/mnt/workspace/import/rmlstreamer-json_mapping_rml_ttl-hgnc.nt/`
containing 8 *files*. You mention 8 *directories*, but I can't reproduce that; 
could you send the log of the Job Manager if that still occors with version 2?

The reason that there are 8 files in a directory is that Flink creates
as many files as parallel tasks.

**Comment by vemonet** [comment]
Hi @ghsnd indeed the use of RMLStreamer v2.0.0 as documented with the `-p` argument fixed my issue and parallelism is now working really well (in `toFile` mode)

Thanks a lot!
