### ISSUE TITLE
Problem with parallel execution

### ISSUE THREAD

**Issue by dchicca** [RMLio/RMLStreamer#27]
Hi,

I am trying to run RMLStreamer in parallel, but it seems that the job always gets **parallelism: 1**. I set in flink configuration **taskmanager.numberOfTaskSlots: 8** and **parallelism.default: 8** but still the result is the same. I have tried both using docker and a local installation of flink. Below is the command I used

```shell
docker exec -it docker_jobmanager_1 /opt/flink/bin/flink run -p 8 -c io.rml.framework.Main /mnt/data/RMLStreamer-2.1.0.jar toFile --mapping-file /mnt/data/mapping.ttl --output-path /mnt/data/output.nt
```
In the dashboard I see **parallelism: 8** under the configuration section of the running job, but in the diagram it is always **1**.

**Comment by ghsnd** [comment]
Hi,

I assume you have one or more files as input. In that case the parallelism depends on the input file format. CSV can be processed by default in parallel by Flink because it's processed row by row, no magic there. XML and JSON are different because what a record is depends on the logical iterator (`rml:iterator`). It can span multiple lines or only a part of a line. There is no logic to chunk according to logical iterators at the moment, so the parallelism is 1.

In case of input *streams* input messages are distributed over the available task slots and thus such a job uses the given parallelism.

I hope this answers your question.

**Comment by dchicca** [comment]
Yes, indeed I was using a JSON as input: by replacing it with a CSV and changing the mappings appropriately, it worked fine.

Thank you
